title: Intro to Boombox LMS
cover-image: boombox.jpg
slug: intro-to-boombox-lms
subtitle: What is it? Why is it? How does it work? Your questions, answered.
group-access-levels:
  assigned:
    - all
