title: Building Apps to Scale
cover-image: building-to-scale.jpg
slug: filler-topic-5
subtitle: "A primer on microservices and other enterprise architecture"
group-access-levels:
  available:
    - all
