title: Observability Planning
cover-image: observability.jpg
slug: filler-topic-10
subtitle: A step-by-step guide to designing a new feature with observability in mind.
group-access-levels:
  available:
    - all
